{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "rvm": [
    "2.2",
    "jruby"
  ],
  "deploy": [
    {
      "provider": "pages",
      "strategy": "git",
      "cleanup": true,
      "keep_history": true,
      "on": {
        "branch": [
          "main"
        ]
      },
      "token": "$GITHUB_TOKEN"
    }
  ]
}
